#!/usr/bin/env python3
"""Regression tests for bootstrap's Git ownership boundary."""
from __future__ import annotations

import contextlib
import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
import uuid
from pathlib import Path
from typing import Iterator
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

import bootstrap  # noqa: E402
import check as gate  # noqa: E402
from tools import native_engine  # noqa: E402
from tools import process_supervisor  # noqa: E402


@contextlib.contextmanager
def _temporary_directory() -> Iterator[str]:
    configured = os.environ.get("KIT_TEST_TMPDIR")
    candidates = ([Path(configured)] if configured else []) + [
        Path(tempfile.gettempdir()),
        Path("/tmp"),
        ROOT / ".checklogs" / "tests",
    ]
    root = None
    for candidate in candidates:
        probe = candidate / f"bootstrap-probe-{uuid.uuid4().hex}"
        try:
            candidate.mkdir(parents=True, exist_ok=True)
            probe.mkdir()
            (probe / "write-check").write_text("ok", encoding="utf-8")
            shutil.rmtree(probe)
            root = candidate
            break
        except OSError:
            shutil.rmtree(probe, ignore_errors=True)
    if root is None:
        raise RuntimeError("no writable bootstrap test scratch directory")
    directory = root / f"bootstrap-{uuid.uuid4().hex}"
    directory.mkdir()
    try:
        yield str(directory)
    finally:
        resolved_root = root.resolve()
        resolved_directory = directory.resolve()
        if resolved_directory.parent == resolved_root:
            shutil.rmtree(resolved_directory, ignore_errors=True)


def _git_executable(repo: Path) -> str:
    return process_supervisor.resolve_ordinary_executable(
        "git", excluded_roots=(repo, ROOT)
    )


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        [_git_executable(repo), "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout


class BootstrapGitSafety(unittest.TestCase):
    def setUp(self) -> None:
        try:
            process_supervisor.resolve_ordinary_executable(
                "git", excluded_roots=(ROOT,)
            )
        except (FileNotFoundError, ValueError):
            self.skipTest("git is not installed")

    def _run_with_unrelated_checks_stubbed(self, repo: Path, *arguments: str) -> int:
        stubbed = (
            "check_python",
            "check_kit_context",
            "check_dependency_lock",
            "check_uv",
            "check_gdtoolkit",
            "check_gut",
            "check_mermaid",
            "check_project_name",
            "check_project_shape",
            "check_warnings_block",
            "check_import",
            "check_editor_settings",
        )
        bootstrap.results.clear()
        with contextlib.ExitStack() as stack:
            # Scratch repositories live below the real checkout when the
            # sandbox denies the system temp directory. Prevent Git from
            # walking past the fixture and mistaking the parent checkout for
            # the repository under test.
            stack.enter_context(mock.patch.dict(
                os.environ,
                {"GIT_CEILING_DIRECTORIES": str(repo.parent.resolve())},
            ))
            stack.enter_context(mock.patch.object(bootstrap, "ROOT", repo))
            stack.enter_context(mock.patch.object(bootstrap, "SRC", repo / "src"))
            stack.enter_context(mock.patch.object(bootstrap, "check_godot", return_value=None))
            stack.enter_context(mock.patch.object(sys, "argv", ["bootstrap.py", *arguments]))
            stack.enter_context(mock.patch.object(
                bootstrap,
                "normalise_formatting",
                side_effect=lambda: (repo / "setup-generated.txt").write_text(
                    "generated by setup\n", encoding="utf-8"
                ),
            ))
            for name in stubbed:
                stack.enter_context(mock.patch.object(bootstrap, name, return_value=None))
            return bootstrap.main()

    def test_target_local_git_command_is_never_started(self) -> None:
        if os.name != "nt":
            return
        with _temporary_directory() as temp:
            repo = Path(temp)
            _git(repo, "init", "--quiet")
            marker = repo / "hijacked.txt"
            (repo / "git.cmd").write_text(
                f'@echo off\r\n>"{marker}" echo hijacked\r\n',
                encoding="utf-8",
            )
            environment = {
                "PATH": str(repo) + os.pathsep + os.environ.get("PATH", "")
            }
            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", repo), mock.patch.dict(
                bootstrap.os.environ, environment, clear=False
            ):
                bootstrap.check_git(initialise=False)
            self.assertFalse(marker.exists())
            self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])

    def test_fix_never_stages_or_commits_an_existing_repository(self) -> None:
        with _temporary_directory() as temp:
            repo = Path(temp)
            _git(repo, "init")
            _git(repo, "config", "user.email", "test@example.invalid")
            _git(repo, "config", "user.name", "Bootstrap Test")
            tracked = repo / "tracked.txt"
            tracked.write_text("baseline\n", encoding="utf-8")
            _git(repo, "add", "tracked.txt")
            _git(repo, "commit", "-m", "baseline")

            tracked.write_text("staged\n", encoding="utf-8")
            _git(repo, "add", "tracked.txt")
            tracked.write_text("working\n", encoding="utf-8")
            (repo / "untracked.txt").write_text("developer work\n", encoding="utf-8")

            before = {
                "head": _git(repo, "rev-parse", "HEAD"),
                "cached": _git(repo, "diff", "--cached", "--binary"),
                "working": _git(repo, "diff", "--binary"),
            }
            status_before = set(_git(repo, "status", "--porcelain=v1").splitlines())

            self.assertEqual(0, self._run_with_unrelated_checks_stubbed(repo, "--fix"))

            after = {
                "head": _git(repo, "rev-parse", "HEAD"),
                "cached": _git(repo, "diff", "--cached", "--binary"),
                "working": _git(repo, "diff", "--binary"),
            }
            self.assertEqual(before, after)
            self.assertEqual(
                status_before,
                set(_git(repo, "status", "--porcelain=v1").splitlines()),
            )
            self.assertEqual("developer work\n", (repo / "untracked.txt").read_text(encoding="utf-8"))

    def test_fix_does_not_initialise_or_commit_a_repository(self) -> None:
        with _temporary_directory() as temp:
            repo = Path(temp)
            (repo / "starter.txt").write_text("kit\n", encoding="utf-8")

            self.assertEqual(1, self._run_with_unrelated_checks_stubbed(repo, "--fix"))

            self.assertFalse((repo / ".git").exists())
            self.assertFalse((repo / "setup-generated.txt").exists())

    def test_init_git_never_stages_or_commits(self) -> None:
        with _temporary_directory() as temp:
            repo = Path(temp)
            (repo / "starter.txt").write_text("kit\n", encoding="utf-8")

            # KIT_TEST_TMPDIR may deliberately be private runtime below the
            # checkout.  This test models a standalone destination, so hide
            # only the physical harness checkout's ancestor marker.  Git is
            # already bounded by GIT_CEILING_DIRECTORIES in the helper above;
            # production bootstrap retains its independent ancestry scan.
            path_exists = Path.exists

            def standalone_exists(path: Path, *args, **kwargs) -> bool:
                if path.name == ".git" and path.parent != repo:
                    return False
                return path_exists(path, *args, **kwargs)

            with mock.patch.object(
                Path, "exists", autospec=True, side_effect=standalone_exists
            ):
                result = self._run_with_unrelated_checks_stubbed(repo, "--init-git")

            self.assertEqual(0, result)
            self.assertTrue((repo / ".git").exists())
            self.assertNotEqual(0, subprocess.run(
                [_git_executable(repo), "-C", str(repo), "rev-parse", "HEAD"],
                capture_output=True,
                check=False,
            ).returncode)
            self.assertEqual(["?? starter.txt"], _git(repo, "status", "--porcelain=v1").splitlines())

    def test_fix_treats_a_linked_worktree_as_existing(self) -> None:
        with _temporary_directory() as temp:
            base = Path(temp)
            primary = base / "primary"
            worktree = base / "linked"
            primary.mkdir()
            _git(primary, "init")
            _git(primary, "config", "user.email", "test@example.invalid")
            _git(primary, "config", "user.name", "Bootstrap Test")
            (primary / "tracked.txt").write_text("baseline\n", encoding="utf-8")
            _git(primary, "add", "tracked.txt")
            _git(primary, "commit", "-m", "baseline")
            _git(primary, "worktree", "add", "-b", "linked-test", str(worktree))

            (worktree / "tracked.txt").write_text("staged\n", encoding="utf-8")
            _git(worktree, "add", "tracked.txt")
            before_head = _git(worktree, "rev-parse", "HEAD")
            before_cached = _git(worktree, "diff", "--cached", "--binary")

            self.assertEqual(0, self._run_with_unrelated_checks_stubbed(worktree, "--fix"))

            self.assertEqual(before_head, _git(worktree, "rev-parse", "HEAD"))
            self.assertEqual(before_cached, _git(worktree, "diff", "--cached", "--binary"))
            self.assertFalse((worktree / "setup-generated.txt").exists())


class BootstrapMutationBoundary(unittest.TestCase):
    def test_json_diagnosis_never_enables_a_mutation(self) -> None:
        bootstrap.results.clear()
        output = io.StringIO()
        with contextlib.ExitStack() as stack:
            stack.enter_context(mock.patch.object(sys, "argv", ["bootstrap.py", "--json"]))
            for name in (
                "check_python", "check_project_shape", "check_warnings_block",
                "check_import", "check_uv", "check_kit_context",
            ):
                stack.enter_context(mock.patch.object(bootstrap, name, return_value=None))
            gdtoolkit = stack.enter_context(mock.patch.object(
                bootstrap, "check_gdtoolkit", return_value=None
            ))
            stack.enter_context(mock.patch.object(bootstrap, "check_dependency_lock", return_value={}))
            git = stack.enter_context(mock.patch.object(bootstrap, "check_git", return_value=False))
            gut = stack.enter_context(mock.patch.object(bootstrap, "check_gut", return_value=None))
            mermaid = stack.enter_context(mock.patch.object(bootstrap, "check_mermaid", return_value=None))
            project_name = stack.enter_context(mock.patch.object(
                bootstrap, "check_project_name", return_value=None
            ))
            editor = stack.enter_context(mock.patch.object(
                bootstrap, "check_editor_settings", return_value=None
            ))
            stack.enter_context(mock.patch.object(bootstrap, "check_godot", return_value=None))
            with contextlib.redirect_stdout(output):
                self.assertEqual(0, bootstrap.main())

        git.assert_called_once_with(initialise=False)
        gdtoolkit.assert_called_once_with({}, install=False)
        gut.assert_called_once_with(download=False, lock={})
        mermaid.assert_called_once_with(download=False, lock={})
        project_name.assert_called_once_with(chosen=None)
        editor.assert_called_once_with(configure=False)

    def test_json_rejects_every_state_changing_option(self) -> None:
        options = (
            ("--download-dep", "gut"),
            ("--download-dep", "gdtoolkit"),
            ("--audit-dependencies",),
            ("--configure-editor",),
            ("--init-git",),
            ("--import-project",),
            ("--format-game",),
            ("--project-name", "A Game"),
            ("--game-layout", "."),
            ("--import-profile", "pixel-art"),
        )
        for option in options:
            with self.subTest(option=option), \
                    mock.patch.object(sys, "argv", ["bootstrap.py", "--json", *option]), \
                    contextlib.redirect_stderr(io.StringIO()), \
                    self.assertRaises(SystemExit) as caught:
                bootstrap.main()
            self.assertEqual(2, caught.exception.code)

    def test_explicit_layout_selects_an_existing_root_project_only(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            config = root / "kit.config.json"
            config.write_text(
                '{"schema":1,"game_root":"src","runtime_root":".kit/runtime"}\n',
                encoding="utf-8",
            )
            (root / "project.godot").write_text("[application]\n", encoding="utf-8")
            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", root), \
                    mock.patch.object(bootstrap, "KIT_CONFIG", config):
                bootstrap.configure_game_layout(".")

            updated = json.loads(config.read_text(encoding="utf-8"))
            self.assertEqual(".", updated["game_root"])
            self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])

    def test_layout_selection_never_creates_or_moves_a_game(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            config = root / "kit.config.json"
            original = '{"schema":1,"game_root":"src","runtime_root":".kit/runtime"}\n'
            config.write_text(original, encoding="utf-8")
            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", root), \
                    mock.patch.object(bootstrap, "KIT_CONFIG", config):
                bootstrap.configure_game_layout(".")

            self.assertEqual(original, config.read_text(encoding="utf-8"))
            self.assertFalse((root / "project.godot").exists())
            self.assertEqual(bootstrap.MANUAL, bootstrap.results[-1]["state"])

    def test_root_layout_routes_gut_checks_to_the_configured_game_root(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            marker = root / ".agent-kit.json"
            config = root / "kit.config.json"
            marker.write_text(
                '{"kind":"portable-agent-kit-root","schema":1}\n',
                encoding="utf-8",
            )
            config.write_text(
                '{"schema":1,"game_root":".","runtime_root":".kit/runtime"}\n',
                encoding="utf-8",
            )
            (root / "project.godot").write_text("[application]\n", encoding="utf-8")
            gut = root / "addons" / "gut"
            gut.mkdir(parents=True)
            (gut / "gut_cmdln.gd").write_text("fixture\n", encoding="utf-8")
            digest = "a" * 64
            lock = {"artifacts": {"gut": {"files": 1, "tree_sha256": digest,
                                           "version": "9.7.1"}}}

            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", root), \
                    mock.patch.object(bootstrap, "SRC", root / "src"), \
                    mock.patch.object(bootstrap, "KIT_MARKER", marker), \
                    mock.patch.object(bootstrap, "KIT_CONFIG", config), \
                    mock.patch.object(
                        bootstrap, "_regular_tree_digest",
                        return_value=(1, 8, digest),
                    ):
                bootstrap.check_kit_context()
                bootstrap.check_gut(download=False, lock=lock)

            self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])
            self.assertIn("locked 9.7.1 tree present", bootstrap.results[-1]["detail"])

    def test_locked_download_rejects_wrong_digest(self) -> None:
        artifact = {
            "url": "https://example.invalid/tool",
            "bytes": 4,
            "sha256": "0" * 64,
        }

        class Response:
            headers = {"Content-Length": "4"}

            def __enter__(self):
                return self

            def __exit__(self, *_args):
                return False

            @staticmethod
            def read(_limit):
                return b"test"

        with mock.patch.object(bootstrap.urllib.request, "urlopen", return_value=Response()):
            with self.assertRaisesRegex(RuntimeError, "SHA-256 mismatch"):
                bootstrap._download_locked(artifact, "test")


class PrivateToolResolution(unittest.TestCase):
    def test_locked_private_files_are_recognised_without_launching_them(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            target = root / "runtime" / "gdtoolkit-4.5.0"
            bindir = target / ("Scripts" if os.name == "nt" else "bin")
            suffix = ".exe" if os.name == "nt" else ""
            gdlint = bindir / f"gdlint{suffix}"
            python = bindir / f"python{suffix}"
            bindir.mkdir(parents=True)
            for executable in (gdlint, python):
                executable.write_bytes(b"ordinary executable fixture")
                executable.chmod(0o755)
            wheel_content = b"authenticated direct wheel"
            wheel = target / "gdtoolkit-4.5.0-py3-none-any.whl"
            wheel.write_bytes(wheel_content)
            lock = {
                "tools": {
                    "gdtoolkit": {
                        "version": "4.5.0",
                        "filename": wheel.name,
                        "bytes": len(wheel_content),
                        "sha256": hashlib.sha256(wheel_content).hexdigest(),
                    }
                }
            }
            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", root), mock.patch.object(
                bootstrap,
                "_gdtoolkit_environment",
                return_value=(target, gdlint, python),
            ), mock.patch.object(bootstrap, "run") as run:
                bootstrap.check_gdtoolkit(lock, install=False)
        self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])
        self.assertIn("not launched during diagnosis", bootstrap.results[-1]["detail"])
        run.assert_not_called()

    def test_changed_private_wheel_is_not_trusted_or_launched(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            target = root / "runtime" / "gdtoolkit-4.5.0"
            bindir = target / ("Scripts" if os.name == "nt" else "bin")
            suffix = ".exe" if os.name == "nt" else ""
            gdlint = bindir / f"gdlint{suffix}"
            python = bindir / f"python{suffix}"
            bindir.mkdir(parents=True)
            for executable in (gdlint, python):
                executable.write_bytes(b"ordinary executable fixture")
                executable.chmod(0o755)
            wheel = target / "gdtoolkit-4.5.0-py3-none-any.whl"
            wheel.write_bytes(b"changed")
            lock = {
                "tools": {
                    "gdtoolkit": {
                        "version": "4.5.0",
                        "filename": wheel.name,
                        "bytes": len(b"expected"),
                        "sha256": hashlib.sha256(b"expected").hexdigest(),
                    }
                }
            }
            bootstrap.results.clear()
            with mock.patch.object(bootstrap, "ROOT", root), mock.patch.object(
                bootstrap,
                "_gdtoolkit_environment",
                return_value=(target, gdlint, python),
            ), mock.patch.object(
                bootstrap,
                "_ordinary_tool",
                side_effect=FileNotFoundError("fixture"),
            ), mock.patch.object(
                bootstrap.importlib.metadata,
                "version",
                side_effect=bootstrap.importlib.metadata.PackageNotFoundError,
            ), mock.patch.object(bootstrap, "run") as run:
                bootstrap.check_gdtoolkit(lock, install=False)
        self.assertEqual(bootstrap.MISSING, bootstrap.results[-1]["state"])
        run.assert_not_called()

    def test_missing_gdtoolkit_is_an_optional_advisory(self) -> None:
        lock = {"tools": {"gdtoolkit": {"version": "4.5.0"}}}
        bootstrap.results.clear()
        with mock.patch.object(
            bootstrap, "_gdtoolkit_environment", side_effect=ValueError("fixture")
        ), mock.patch.object(
            bootstrap,
            "_ordinary_tool",
            side_effect=FileNotFoundError("fixture"),
        ), mock.patch.object(
            bootstrap.importlib.metadata,
            "version",
            side_effect=bootstrap.importlib.metadata.PackageNotFoundError,
        ):
            bootstrap.check_gdtoolkit(lock, install=False)

        result = bootstrap.results[-1]
        self.assertEqual(bootstrap.MISSING, result["state"])
        self.assertTrue(result["advisory"])
        self.assertIn("optional style adapter", result["detail"])

    def test_gate_prefers_the_exact_project_private_formatter(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            config = root / "kit.config.json"
            config.write_text(
                '{"schema":1,"runtime_root":".kit/runtime"}\n', encoding="utf-8"
            )
            suffix = ".exe" if os.name == "nt" else ""
            tool = (root / ".kit" / "runtime" / "tooling" / "gdtoolkit-4.5.0"
                    / ("Scripts" if os.name == "nt" else "bin")
                    / f"gdlint{suffix}")
            tool.parent.mkdir(parents=True)
            tool.write_bytes(b"fixture")
            tool.chmod(0o755)
            probe = subprocess.CompletedProcess(
                [str(tool), "--version"], 0, stdout="gdlint 4.5.0\n", stderr=""
            )
            with mock.patch.object(gate, "ROOT", root), \
                    mock.patch.object(gate, "KIT_CONFIG_FILE", config), \
                    mock.patch.object(gate, "GDTOOLKIT_VERSION", "4.5.0"), \
                    mock.patch.object(gate.subprocess, "run", return_value=probe) as run:
                resolved = gate.gdtool("gdlint")

        self.assertEqual([str(tool)], resolved)
        run.assert_called_once()

    def test_gdtoolkit_transitives_resolve_only_from_canonical_pypi(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            target = root / "gdtoolkit-4.5.0"
            bindir = target / ("Scripts" if os.name == "nt" else "bin")
            suffix = ".exe" if os.name == "nt" else ""
            lock = {
                "tools": {
                    "gdtoolkit": {
                        "version": "4.5.0",
                        "filename": "gdtoolkit-4.5.0-py3-none-any.whl",
                    }
                }
            }
            bootstrap.results.clear()
            with mock.patch.object(
                bootstrap,
                "_gdtoolkit_environment",
                return_value=(
                    target,
                    bindir / f"gdlint{suffix}",
                    bindir / f"python{suffix}",
                ),
            ), mock.patch.object(
                bootstrap,
                "_download_locked",
                return_value=b"authenticated direct wheel",
            ), mock.patch.object(
                bootstrap,
                "run",
                side_effect=((0, ""), (0, ""), (0, "gdlint 4.5.0\n")),
            ) as run, mock.patch.object(
                bootstrap, "QUIET", True
            ), mock.patch.dict(
                bootstrap.os.environ,
                {
                    "PIP_EXTRA_INDEX_URL": "https://untrusted.example/simple",
                    "PIP_INDEX_URL": "https://untrusted.example/simple",
                },
            ):
                bootstrap._install_gdtoolkit(lock)

        self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])
        self.assertEqual(
            [
                process_supervisor.isolated_python_executable(sys.executable),
                "-B", "-I", "-S", "-m", "venv", "--copies",
            ],
            run.call_args_list[0].args[0][:-1],
        )
        self.assertEqual(str(target), run.call_args_list[0].args[0][-1])
        pip_call = run.call_args_list[1]
        self.assertEqual(
            [
                str(target / ("Scripts" if os.name == "nt" else "bin")
                    / f"python{suffix}"),
                "-I",
                "-m",
                "pip",
                "--isolated",
                "install",
                "--disable-pip-version-check",
                "--no-input",
                "--no-cache-dir",
                "--only-binary=:all:",
                "--index-url",
                "https://pypi.org/simple",
                str(target / "gdtoolkit-4.5.0-py3-none-any.whl"),
            ],
            pip_call.args[0],
        )
        self.assertEqual(600, pip_call.kwargs["timeout"])
        environment = pip_call.kwargs["environment"]
        self.assertEqual(os.devnull, environment["PIP_CONFIG_FILE"])
        self.assertEqual(
            ["PIP_CONFIG_FILE"],
            sorted(key for key in environment if key.upper().startswith("PIP_")),
        )


class DependencyProvenance(unittest.TestCase):
    def test_regular_tree_digest_has_a_stable_cross_platform_fixture(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            (root / "nested").mkdir()
            (root / "a.txt").write_bytes(b"A\n")
            (root / "nested" / "b.bin").write_bytes(bytes((0, 255)))

            count, total, digest = bootstrap._regular_tree_digest(root)

        self.assertEqual(2, count)
        self.assertEqual(4, total)
        self.assertEqual(
            "b364a64e14e9d1bf7fd0c82fe61524c15e38a54dbd522845daa08169e224e3c0",
            digest,
        )

    def test_source_audit_authenticates_every_direct_locked_artifact(self) -> None:
        lock = {
            "tools": {"gdtoolkit": {"version": "4.5.0"}},
            "artifacts": {
                "gut": {"version": "9.7.1"},
                "mermaid": {
                    "version": "11.17.1",
                    "member": "package/dist/mermaid.min.js",
                    "member_bytes": 2,
                    "member_sha256": "a" * 64,
                    "license_member": "package/LICENSE",
                    "license_bytes": 3,
                    "license_sha256": "b" * 64,
                },
            },
        }
        bootstrap.results.clear()
        with mock.patch.object(
            bootstrap,
            "_download_locked",
            side_effect=(b"wheel", b"gut", b"mermaid"),
        ) as download, mock.patch.object(
            bootstrap, "_gut_archive_payloads", return_value=[("gut_cmdln.gd", b"x")]
        ) as gut, mock.patch.object(
            bootstrap, "_tar_member", return_value=b"fixture"
        ) as tar:
            bootstrap.audit_dependencies(lock)

        self.assertEqual(bootstrap.OK, bootstrap.results[-1]["state"])
        self.assertEqual(["gdtoolkit", "GUT", "mermaid"], [
            call.args[1] for call in download.call_args_list
        ])
        gut.assert_called_once_with(b"gut", lock["artifacts"]["gut"])
        self.assertEqual(2, tar.call_count)


class IntegrityManifestTrust(unittest.TestCase):
    def test_bootstrap_never_invokes_the_human_acceptance_flag(self) -> None:
        source = Path(bootstrap.__file__).read_text(encoding="utf-8")
        self.assertNotIn("--accept-gate-changes", source)

    def test_missing_manifest_fails_closed_without_creating_one(self) -> None:
        with _temporary_directory() as temp:
            manifest = Path(temp) / ".gate.sha256"
            results = gate.Results()
            output = io.StringIO()
            with mock.patch.object(gate, "MANIFEST_FILE", manifest), \
                    mock.patch.object(gate, "RESULTS", results), \
                    contextlib.redirect_stdout(output):
                gate.stage_integrity()

            self.assertTrue(results.failed)
            self.assertFalse(manifest.exists())
            self.assertIn("MISSING", output.getvalue())
            self.assertIn("manifest missing", "\n".join(results.lines))

    def test_incomplete_manifest_cannot_omit_a_gate_file(self) -> None:
        with _temporary_directory() as temp:
            root = Path(temp)
            manifest = root / ".gate.sha256"
            manifest.write_text(
                "# deliberately truncated manifest\n", encoding="utf-8"
            )
            results = gate.Results()
            output = io.StringIO()
            with mock.patch.object(gate, "ROOT", root), \
                    mock.patch.object(gate, "PROJECT_DIR", root / "src"), \
                    mock.patch.object(gate, "MANIFEST_FILE", manifest), \
                    mock.patch.object(gate, "GATE_FILES", ["check.py"]), \
                    mock.patch.object(gate, "ADVISORY_FILES", []), \
                    mock.patch.object(gate, "RESULTS", results), \
                    contextlib.redirect_stdout(output):
                gate.stage_integrity()

            self.assertTrue(results.failed)
            self.assertIn("UNLISTED  check.py", output.getvalue())
            self.assertIn("manifest incomplete", "\n".join(results.lines))


class EngineLaunchSerialization(unittest.TestCase):
    def test_only_one_process_can_hold_the_godot_launch_lock(self) -> None:
        with _temporary_directory() as temp:
            lock = Path(temp) / "runtime" / "godot-process.lock"
            with mock.patch.object(native_engine, "engine_lock_path", return_value=lock):
                first, problem = native_engine.acquire_engine_lock(ROOT)
                self.assertIsNotNone(first, problem)
                second, problem = native_engine.acquire_engine_lock(ROOT)
                self.assertIsNone(second)
                self.assertIn("another Godot launch", problem)
                native_engine.release_engine_lock(ROOT, "not-the-owner")
                self.assertTrue(lock.exists())
                native_engine.release_engine_lock(ROOT, first)
                self.assertFalse(lock.exists())

    def test_stale_process_lock_is_recovered_once(self) -> None:
        with _temporary_directory() as temp:
            lock = Path(temp) / "runtime" / "godot-process.lock"
            warning = Path(temp) / "runtime" / "native-warning.json"
            lock.parent.mkdir(parents=True)
            identity = native_engine.ProcessIdentity(
                2147483647,
                "test",
                "stale-owner",
                "a" * 64,
                "Godot.exe",
            )
            lock.write_text(
                json.dumps(
                    {
                        "schema": 2,
                        "pid": 2147483647,
                        "token": "stale",
                        "process_identity": identity.as_json(),
                    }
                ) + "\n",
                encoding="utf-8",
            )
            with mock.patch.object(
                native_engine, "engine_lock_path", return_value=lock
            ), mock.patch.object(
                native_engine, "native_warning_path", return_value=warning
            ), mock.patch.object(
                native_engine, "_pid_liveness", return_value=native_engine.PID_DEAD
            ):
                token, problem = native_engine.acquire_engine_lock(ROOT)
                self.assertIsNone(token)
                self.assertIn("triggering launch was refused", problem)
                self.assertTrue(warning.exists())
                token, problem = native_engine.acquire_engine_lock(ROOT)
                self.assertIsNotNone(token, problem)
                native_engine.release_engine_lock(ROOT, token)
            self.assertFalse(lock.exists())


if __name__ == "__main__":
    unittest.main()
